name: Build image for Yandex Cloud

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  REGISTRY: cr.yandex
  REGISTRY_ID: crp301cug6i0d7dn4747
  IMAGE_NAME: repanel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Yandex Container Registry
        uses: yc-actions/yc-cr-login@v3
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ env.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            NEXT_PUBLIC_SITE_URL=https://www.re-panel.ru
            SITE_STORAGE_PUBLIC_BASE_URL=${{ vars.SITE_STORAGE_PUBLIC_BASE_URL }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
